public class names {
	
	public static String tlnames[] = {
		"Bibliya",
		"lumabas",
		"Kabanata",
		"aklat",
		"Tipan",
		"teksto",
		"pumili",
		"Lumang Tipan",
		"Bagong Tipan",
		"Mga Awit",
		"Ebanghelyo",
		//4 добавленных значения ниже ///////////////////////
		"Mga Resulta sa Paghahanap",	//<string name="findresults">
		"posporo",			//<string name="matches">
		"Tula",					//<string name="poem">
		"Hanapin"					//<string name="searchbutton">
		};	
	
	public static String tlbible[] = {	
		"Genesis",
		"Exodo",
		"Levitico",
		"Levitico",
		"Deuteronomio",
		"Josue",
		"Mga Hukomt",
		"Ruth",
		"1 Samuel",
		"2 Sa-mu-ên",
		"1 Mga Hari",
		"2 Mga Hari",
		"1 Mga Cronica",
		"1 Mga Cronica",
		"Ezra",
		"Nehemias",
		"Ester",
		"Job",
		"Mga Awit",
		"Mga Kawikaan",
		"Ang Mangangaral",
		"Ang Awit ni Solomon",
		"Isaias",
		"Jeremias",
		"Mga Panaghoy",
		"Ezekiel",
		"Daniel",
		"Hosea",
		"Joel",
		"Amos",
		"Obadias",
		"Jonas",
		"Mikas",
		"Nahum",
		"Habakkuk",
		"Zefanias",
		"Hagai",
		"Zacarias",
		"Malakias",
		"Mateo",
		"Marcos",
		"Lucas",
		"Juan",
		"Mga Gawa",
		"Mga Taga-Roma",
		"1 Mga Taga-Corinto",
		"2 Mga Taga-Corinto",
		"Mga Taga-Galacia",
		"Mga Taga-Efeso",
		"Mga Taga-Filipos",
		"Mga Taga-Colosas",
		"1 Mga Taga-Tesalonica",
		"2 Mga Taga-Tesalonica",
		"1 Timoteo",
		"2 Timoteo",
		"Tito",
		"Filemon",
		"Mga Hebreo",
		"Santiago",
		"1 Pedro",
		"2 Pedro",
		"1 Juan",
		"2 Juan",
		"3 Juan",
		"Judas",
		"Pahayag"
	};
	
	
	public static String lanames[] = {
		"Biblia Sacra",
		"exitus",
		"capitulum",
		"liber",
		"TESTAMENTUM",
		"text",
		"eligere",
		"VETUS TESTAMENTUM",
		"NOVUM TESTAMENTUM",
		"Psalmus",
		"Evangelium",
		//4 добавленных значения ниже ///////////////////////
		"quaero praecessi",	//<string name="findresults">
		"Matches",			//<string name="matches">
		"poem",					//<string name="poem">
		"Invenies"					//<string name="searchbutton">
	};	
	
	public static String labible[] = {
		"Liber Genesis",
		"Liber Exodus",
		"Liber Leviticus",
		"Liber Numeri",
		"Liber Deuteronomii",
		"Liber Iosue",
		"Liber Iudicum",
		"Liber Ruth",
		"Liber I Samuelis",
		"Liber II Samuelis",
		"Liber I Regum",
		"Liber II Regum",
		"Liber I Paralipomenon",
		"Liber II Paralipomenon",
		"Liber Esdrae",
		"Liber Nehemiae",
		"Liber Esther",
		"Liber Iob",
		"Liber Psalmorum",
		"Liber Proverbiorum",
		"Liber Ecclesiastes",
		"Canticum Canticorum",
		"Liber Isaiae",
		"Liber Ieremiae",
		"Lamentationes",
		"Prophetia Ezechielis",
		"Prophetia Danielis",
		"Prophetia Osee",
		"Prophetia Ioel",
		"Prophetia Amos",
		"Prophetia Abdiae",
		"Prophetia Ionae",
		"Prophetia Michaeae",
		"Prophetia Nahum",
		"Prophetia Habacuc",
		"Prophetia Sophoniae",
		"Prophetia Aggaei",
		"Prophetia Zachariae",
		"Prophetia Malachiae",
		"Evangelium secundum Matthaeum",
		"Evangelium secundum Marcum",
		"Evangelium secundum Lucam",
		"Evangelium secundum Ioannem",
		"Actus Apostolorum",
		"Epistula ad Romanos",
		"Epistula I ad Corinthios",
		"Epistula II ad Corinthios",
		"Epistula ad Galatas",
		"Epistula ad Ephesios",
		"Epistula ad Philippenses",
		"Epistula ad Colossenses",
		"Epistula I ad Thessalonicenses",
		"Epistula II ad Thessalonicenses",
		"Epistula I ad Timotheum",
		"Epistula II ad Timotheum",
		"Epistula ad Titum",
		"Epistulam ad Philemonem",
		"Epistula ad Hebraeos",
		"Epistula Iacobi",
		"Epistula I Petri",
		"Epistula II Petri",
		"Epistula I Ioannis",
		"Epistula II Ioannis",
		"Epistula III Ioannis",
		"Epistula Iudae",
		"Apocalypsis Ioannis"
	};	
	
	public static String swnames[] = {
		"Biblia Takatifu",
		"exit",
		"sura ya",
		"kitabu",
		"Agano",
		"Nakala",
		"kuchagua",
		"Agano la kale",
		"Agano Jipya",
		"zaburi",
		"Injili",
		//4 добавленных значения ниже ///////////////////////
		"Matokeo",	//<string name="findresults">
		"mechi",			//<string name="matches">
		"Shairi",				//<string name="poem">
		"kupata"			//<string name="searchbutton">
	};
	
	public static String swbible[] = {
		"Mwanzo",
		"Kutoka",
		"Mambo ya Walawi",
		"Hesabu",
		"Kumbukumbu la Torati",
		"Yoshua",
		"Waamuzi",
		"Ruthu",
		"1 Samweli",
		"2 Samweli",
		"1 Wafalme",
		"2 Wafalme",
		"1 Mambo ya Nyakati",
		"2 Mambo ya Nyakati",
		"Ezra",
		"Nehemia",
		"Esta",
		"Ayubu",
		"Zaburi",
		"Mithali",
		"Mhubiri",
		"Wimbo Ulio Bora",
		"Isaya",
		"Yeremia",
		"Maombolezo",
		"Ezekieli",
		"Danieli",
		"Hosea",
		"Yoeli",
		"Amosi",
		"Obadia",
		"Yona",
		"Mika",
		"Nahumu",
		"Habakuki",
		"Sefania",
		"Hagai",
		"Zekaria",
		"Malaki",
		"Mathayo",
		"Marko",
		"Luka",
		"Yohana",
		"Matendo ya Mitume",
		"Warumi",
		"1 Wakorintho",
		"2 Wakorintho",
		"Wagalatia",
		"Waefeso",
		"Wafilipi",
		"Wakolosai",
		"1 Wathesalonike",
		"2 Wathesalonike",
		"1 Timotheo",
		"2 Timotheo",
		"Tito",
		"Filemoni",
		"Waebrania",
		"Yakobo",
		"1 Petro",
		"2 Petro",
		"1 Yohana",
		"2 Yohana",
		"3 Yohana",
		"Yuda",
		"Ufunuo wa Yohana"
	};	
	
	public static String afnames[] = {
		"Bybel",
		"verlaat",
		"Hoofstuk",
		"boek",
		"Testament",
		"teks",
		"kies",
		"Die Ou Testament",
		"Die Nuwe Testament",
		"Psalm",
		"Gospel",
		//4 добавленных значения ниже ///////////////////////
		"resultaat",			//<string name="findresults">
		"wedstryde",			//<string name="matches">
		"Gedig",				//<string name="poem">
		"vind"					//<string name="searchbutton">
	};
	
	public static String afbible[] = {
		"Genesis",
		"Eksodus",
		"Levitikus",
		"Numeri",
		"Deuteronomium",
		"Josua",
		"Rigters",
		"Rut",
		"1 Samuel",
		"2 Samuel",
		"1 Konings",
		"2 Konings",
		"1 Kronieke",
		"2 Kronieke",
		"Esra",
		"Nehemia",
		"Ester",
		"Job",
		"Psalms",
		"Spreuke van Salomo",
		"Prediker",
		"Hooglied van Salomo",
		"Jesaja",
		"Jeremia",
		"Klaagliedere van Jeremia",
		"Esegiël",
		"Daniël",
		"Hosea",
		"Joël",
		"Amos",
		"Obadja",
		"Jona",
		"Miga",
		"Nahum",
		"Habakuk",
		"Sefanja",
		"Haggai",
		"Sagaria",
		"Maleagi",
		"Matteus",
		"Markus",
		"Lukas",
		"Johannes",
		"أDie handelinge van die apostels",
		"Romeine - Romans",
		"1 Korintiërs",
		"2 Korintiërs",
		"Galasiërs",
		"Effesiërs",
		"Filippense",
		"Kolossense",
		"1 Tessalonisense",
		"2 Tessalonisense",
		"1 Timoteus",
		"2 Timoteus",
		"Titus",
		"Filemon",
		"Hebreërs",
		"Jakobus",
		"1 Petrus",
		"2 Petrus",
		"1 Johannes",
		"2 Johannes",
		"3 Johannes",
		"Judas",
		"Die openbaring"
	};	
	
	public static String amnames[] = {
		"መጽሐፍ ቅዱስ",
		"መውጫ",
		"ምዕራፍ",
		"መጽሐፈ",
		"ኪዳን",
		"ማደት",
		"መረጠ",
		"ብሉይ ኪዳን",
		"አዲስ ኪዳን",
		"መዝሙር",
		"ወንጌል",
		//4 добавленных значения ниже ///////////////////////
		"ፍለጋ ፍጻሜ",			//<string name="findresults">
		"ፍሬ",				//<string name="matches">
		"ስንኝ",				//<string name="poem">
		"ፈልግ"				//<string name="searchbutton">
	};	
	
	public static String ambible[] = {	
		"ኦሪት ዘፍጥረት",
		"ኦሪት ዘጸአት",
		"ኦሪት ዘሌዋውያን",
		"ኦሪት ዘኍልቍ",
		"ኦሪት ዘዳግም",
		"መጽሐፈ ኢያሱ ወልደ ነዌ",
		"መጽሐፈ መሣፍንት",
		"መጽሐፈ ሩት",
		"መጽሐፈ ሳሙኤል ቀዳማዊ",
		"መጽሐፈ ሳሙኤል ካል",
		"መጽሐፈ ነገሥት ቀዳማዊ።",
		"መጽሐፈ ነገሥት ካልዕ።",
		"መጽሐፈ ዜና መዋዕል ቀዳማዊ።",
		"መጽሐፈ ዜና መዋዕል ካልዕ።",
		"መጽሐፈ ዕዝራ።",
		"መጽሐፈ ነህምያ።",
		"መጽሐፈ አስቴር።",
		"መጽሐፈ ኢዮብ።",
		"መዝሙረ ዳዊት",
		"መጽሐፈ ምሳሌ",
		"መጽሐፈ መክብብ",
		"መኃልየ መኃልይ ዘሰሎሞን",
		"ትንቢተ ኢሳይያስ",
		"ትንቢተ ኤርምያስ",
		"ሰቆቃው ኤርምያስ",
		"ትንቢተ ሕዝቅኤል",
		"ትንቢተ ዳንኤል",
		"ትንቢተ ሆሴዕ",
		"ትንቢተ ኢዮኤል",
		"ትንቢተ አሞጽ",
		"ትንቢተ አብድዩ",
		"ትንቢተ ዮናስ",
		"ትንቢተ ሚክያስ",
		"ትንቢተ ናሆም",
		"ትንቢተ ዕንባቆም",
		"ትንቢተ ሶፎንያስ",
		"ትንቢተ ሐጌ",
		"ትንቢተ ዘካርያስ",
		"ትንቢተ ሚልክያ",
		"﻿የማቴዎስ ወንጌል",
		"የማርቆስ ወንጌል",
		"የሉቃስ ወንጌል",
		"የዮሐንስ ወንጌል",
		"የሐዋርያት ሥራ",
		"ወደ ሮሜ ሰዎች",
		"1ኛ ወደ ቆሮንቶስ ሰዎች",
		"2ኛ ወደ ቆሮንቶስ ሰዎች",
		"ወደ ገላትያ ሰዎች",
		"ወደ ኤፌሶን ሰዎች",
		"ወደ ፊልጵስዩስ ሰዎች",
		"ወደ ቆላስይስ ሰዎች",
		"1ኛ ወደ ተሰሎንቄ ሰዎች",
		"2ኛ ወደ ተሰሎንቄ ሰዎች",
		"1ኛ ወደ ጢሞቴዎስ",
		"2ኛ ወደ ጢሞቴዎስ",
		"ወደ ቲቶ",
		"ወደ ፊልሞና",
		"ወደ ዕብራውያን",
		"የያዕቆብ መልእክት",
		"1ኛ የጴጥሮስ መልእክት",
		"2ኛ የጴጥሮስ መልእክት",
		"1ኛ የዮሐንስ መልእክት",
		"2ኛ የዮሐንስ መልእክት",
		"3ኛ የዮሐንስ መልእክት",
		"የይሁዳ መልእክት",
		"የዮሐንስ ራእይ"
	};	
	
	public static String isnames[] = {
		"Biblían",
		"framleiðsla",
		"Kafli",
		"Bók",
		"Testamentið",
		"texti",
		"velja",
		"Gamla Testamentið",
		"Nýja Testamentið",
		"Sálmur",
		"Gospel",
		//4 добавленных значения ниже ///////////////////////
		"Leitarniðurstöður",	//<string name="findresults">
		"samsvaranir",			//<string name="matches">
		"Ljóð",					//<string name="poem">
		"Leita"					//<string name="searchbutton">
		};
	
	
	public static String isbible[] = {	
		"1. Mósebók",
		"2. Mósebók",
		"3. Mósebók",
		"4. Mósebók",
		"5. Mósebók",
		"Jósúabók",
		"Dómarabók",
		"Rutarbók",
		"Fyrri Samúelsbók",
		"Síðari Samúelsbók",
		"Fyrri Konungabók",
		"Síðari Konungabók",
		"Fyrri Kroníkubók",
		"Síðari Kroníkubók",
		"Esrabók",
		"Nehemíabók",
		"Esterarbók",
		"Jobsbók",
		"Sálmarnir",
		"Orðskviðirnir",
		"Prédikarinn",
		"Ljóðaljóðin",
		"Jesaja",
		"Jeremía",
		"Harmljóðin",
		"Esekíel",
		"Daníel",
		"Hósea",
		"Jóel",
		"Amos",
		"Óbadía",
		"Jónas",
		"Míka",
		"Nahúm",
		"Habakkuk",
		"Sefanía",
		"Haggaí",
		"Sakaría",
		"Malakí",
		"Matteusarguðspjall",
		"Markúsarguðspjall",
		"Lúkasarguðspjall",
		"Jóhannesarguðspjall",
		"Postulasagan",
		"Rómverjabréfið",
		"Fyrra bréf Páls til Korintumanna",
		"Síðara bréf Páls til Korintumanna",
		"Bréf Páls til Galatamanna",
		"Bréf Páls til Efesusmanna",
		"Bréf Páls til Filippímanna",
		"Bréf Páls til Kólossumanna",
		"Fyrra bréf Páls til Þessaloníkumanna",
		"Síðara bréf Páls til Þessaloníkumanna",
		"Fyrra bréf Páls til Tímóteusar",
		"Síðara bréf Páls til Tímóteusar",
		"Bréf Páls til Títusar",
		"Bréf Páls til Fílemons",
		"Bréfið til Hebrea",
		"Hið almenna bréf Jakobs",
		"Fyrra almenna bréf Péturs",
		"Síðara almenna bréf Péturs",
		"Fyrsta bréf Jóhannesar hið almenna",
		"Annað bréf Jóhannesar",
		"Þriðja bréf Jóhannesar",
		"Hið almenna bréf Júdasar",
		"Opinberunarbók Jóhannesar"
	};	
	
	public static String sknames[] = {
		"Biblia",
		"výkon",
		"Kapitola",
		"kniha",
		"Zmluva",
		"text",
		"vybrať",
		"Stará Zmluva",
		"Nová Zmluva",
		"žalm",
		"Evanjelium",
		//4 добавленных значения ниже ///////////////////////
		"Výsledky vyhľadávania",	//<string name="findresults">
		"Zápas",					//<string name="matches">
		"verš",						//<string name="poem">
		"Nájsť"						//<string name="searchbutton">
		};	
	
	public static String skbible[] = {
		"1. Mojžišova",
		"2. Mojžišova",
		"3. Mojžišova",
		"4. Mojžišova",
		"5. Mojžišova",
		"Józua",
		"Sudcov",
		"Rút",
		"1. Samuelova",
		"2. Samuelova",
		"1. Kráľov",
		"2. Kráľov",
		"1. Kronická",
		"2. Kronická",
		"Ezdráš",
		"Nehemiáš",
		"Ester",
		"Jób",
		"Žalmy",
		"Príslovia",
		"Kazateľ",
		"Pieseň",
		"Izaiáš",
		"Jeremiáš",
		"Plač",
		"Ezechiel",
		"Daniel",
		"Hozeáš",
		"Joel",
		"Ámos",
		"Obediáš",
		"Jonáš",
		"Micheáš",
		"Náhum",
		"Habakuk",
		"Sofoniáš",
		"Haggeus",
		"Zachariáš",
		"Malachiáš",
		"Matúš",
		"Marek",
		"Lukáš",
		"Ján",
		"Skutky",
		"Rimanom",
		"1. Korintským",
		"2. Korintským",
		"Galatským",
		"Efezským",
		"Filipským",
		"Kolosenským",
		"1. Tesalonickým",
		"2. Tesalonickým",
		"1. Timoteovi",
		"2. Timoteovi",
		"Títovi",
		"Filemonovi",
		"Židom",
		"Jakubov",
		"1. Petrov",
		"2. Petrov",
		"1. Jánov",
		"2. Jánov",
		"3. Jánov",
		"Júdov",
		"Zjavenie"
	};	
	
	public static String srnames[] = {
		"Библија",
		"излаз",
		"Поглавље",
		"Књига",
		"Завет",
		"текст",
		"изабрати",
		"Стари Завет",
		"Нови Завет",
		"псалм",
		"Јеванђеље",
		//4 добавленных значения ниже ///////////////////////
		"Сеарцх Ресултс",	//<string name="findresults">
		"Шибице",			//<string name="matches">
		"стих",				//<string name="poem">
		"Наћи"				//<string name="searchbutton">
	};	
	
	public static String srbible[] = {
		"Постање",
		"Излазак",
		"Левитска",
		"Бројеви",
		"Поновљени закони",
		"Исус Навин",
		"Судије",
		"Рута",
		"Прва Самуилова",
		"Друга Самуилова",
		"Прва о царевима",
		"Друга о царевима",
		"Прва дневника",
		"Друга дневника",
		"Јездра",
		"Немија",
		"Јестира",
		"Јов",
		"Псалми Давидови",
		"Приче Соломунове",
		"Проповједник",
		"Пјесма над пјесмама",
		"Исаија",
		"Јеремија",
		"Плач Јеремијин",
		"Језекиљ",
		"Данило",
		"Осија",
		"Јоил",
		"Амос",
		"Авдије",
		"Јона",
		"Михеј",
		"Наум",
		"Авакум",
		"Софоније",
		"Агеј",
		"Захарија",
		"Малахија",
		"Матеја",
		"Марко",
		"Лука",
		"Јован",
		"Дела апостолска",
		"Римљанима",
		"1. Коринћанима",
		"2. Коринћанима",
		"Галатима",
		"Ефесцима",
		"Филипљанима",
		"Колошанима",
		"1. Солуњанима",
		"2. Солуњанима",
		"1. Тимотеју",
		"2. Тимотеју",
		"Титу",
		"Филимону",
		"Јеврејима",
		"Јаковљева",
		"1. Петрова",
		"2. Петрова",
		"1. Јованова",
		"2. Јованова",
		"3. Јованова",
		"Јудина",
		"Откривење Јованово"
	};	
	
	public static String mknames[] = {
		"Библија",
		"излез",
		"Глава",
		"книга",
		"Завет",
		"текст",
		"изберете",
		"Стар Завет",
		"Новиот Завет",
		"псалм",
		"Евангелието",
		//4 добавленных значения ниже ///////////////////////
		"Резултати од пребарувањето",	//<string name="findresults">
		"Натпревари",					//<string name="matches">
		"стих",							//<string name="poem">
		"Најди"							//<string name="searchbutton">
		};	
	
	public static String mkbible[] = {
		"Битие",
		"Излез",
		"Левит",
		"Броеви",
		"Второзаконие",
		"Исус Навин",
		"Судии	",
		"Рут",
		"1 Самуил",
		"2 Самуил",
		"1 Цареви",
		"2 Цареви",
		"1 Летописи",
		"2 Летописи",
		"Езра",
		"Неемија",
		"Естира",
		"Јов",
		"Псалми",
		"Пословици",
		"Проповедник",
		"Песна над песните",
		"Исаија",
		"Еремија",
		"Плач Еремиин",
		"Езекиел",
		"Даниел",
		"Осија",
		"Јоил",
		"Амос",
		"Авдиј",
		"Јона",
		"Михеј",
		"Наум",
		"Хабакук",
		"Софонија",
		"Агеј",
		"Захарија",
		"Малахија",
		"Матеј",
		"Марко",
		"Лука",
		"Јован",
		"Дела Ап.",
		"Јаков",
		"1 Петрово	",
		"2 Петрово",
		"1 Јованово",
		"2 Јованово",
		"3 Јованово",
		"Јуда",
		"Римјаните",
		"1 Коринтјани",
		"2 Коринтјани",
		"Галатјани",
		"Ефесјани",
		"Филипјани",
		"Колосјани",
		"1 Солунјани",
		"2 Солунјани",
		"1 Тимотеј",
		"2 Тимотеј",
		"Тит	",
		"Филимон",
		"Евреите",
		"Откровение"		
	};	
	
	public static String plnames[] = {
		"Biblia, Pismo Święte",
		"wyjście",
		"Rozdział",
		"Księga",
		"Testament",
		"tekst",
		"wybrać",
		"Stary Testament",
		"Nowy Testament",
		"psalm",
		"Ewangelia",
		//4 добавленных значения ниже ///////////////////////
		"Wyniki wyszukiwania",				//<string name="findresults">
		"mecze",							//<string name="matches">
		"wiersz",							//<string name="poem">
		"Szukaj"							//<string name="searchbutton">
		};	
	
	public static String plbible[] = {
		"Księga Rodzaju",
		"Księga Wyjścia",
		"Księga Kapłańska",
		"Księga Liczb",
		"Księga Powtórzonego Prawa",
		"Księga Jozuego",
		"Księga Sędziów",
		"Księga Rut",
		"1 Księga Samuela",
		"2 Księga Samuela",
		"1 Księga Królewska",
		"2 Księga Królewska",
		"1 Księga Kronik",
		"2 Księga Kronik",
		"Księga Ezdrasza",
		"Księga Nehemiasza",
		"Księga Estery",
		"Księga Hioba",
		"Księga Psalmów",
		"Księga Przysłów",
		"Księga Koheleta",
		"Pieśń nad Pieśniami",
		"Księga Izajasza",
		"Księga Jeremiasza",
		"Lamentacje",
		"Księga Ezechiela",
		"Księga Daniela",
		"Księga Ozeasza",
		"Księga Joela",
		"Księga Amosa",
		"Księga Abdiasza",
		"Księga Jonasza",
		"Księga Micheasza",
		"Księga Nahuma",
		"Księga Habakuka",
		"Księga Sofoniasza",
		"Księga Aggeusza",
		"Księga Zachariasza",
		"Księga Malachiasza",
		"Ewangelia wg św.Mateusza",
		"Ewangelia wg św.Marka",
		"Ewangelia wg św.Łukasza",
		"Ewangelia wg św.Jana",
		"Dzieje Apostolskie",
		"List do Rzymian",
		"1 List do Koryntian",
		"2 List do Koryntian",
		"List do Galatów",
		"List do Efezjan",
		"List do Filipian",
		"List do Kolosan",
		"1 List do Tesaloniczan",
		"2 List do Tesaloniczan",
		"1 List do Tymoteusza",
		"2 List do Tymoteusza",
		"List do Tytusa",
		"List do Filemona",
		"List do Hebrajczyków",
		"List św. Jakuba",
		"1 List św. Piotra",
		"2 List św. Piotra",
		"1 List św. Jana",
		"2 List św. Jana",
		"3 List św. Jana",
		"List św. Judy",
		"Apokalipsa św. Jana"
	};
	
	
	public static String ltnames[] = {
		"Biblija",
		"iš",
		"Skyrius",
		"knyga",
		"Testamentas",
		"tekstas",
		"pasirinkti",
		"Senasis Testamentas",
		"Naujasis Testamentas",
		"psalmė",
		"Evangelija",
		//4 добавленных значения ниже ///////////////////////
		"Paieškos rezultatai",				//<string name="findresults">
		"degtukai",							//<string name="matches">
		"Eilėraštis",						//<string name="poem">
		"rasti"								//<string name="searchbutton">
		};	
	
	public static String ltbible[] = {
		"Pradžios knyga",
		"Išėjimo knyga",
		"Kunigų (Levitų) knyga",
		"Skaičių knyga",
		"Pakartoto Įstatymo knyga",
		"Jozuės knyga",
		"Teisėjų knyga",
		"Rūtos knyga",
		"Pirmoji Samuelio knyga",
		"Antroji Samuelio knyga",
		"Pirmoji Karalių knyga",
		"Antroji Karalių knyga",
		"Pirmoji Kronikų knyga",
		"Antroji Kronikų knyga",
		"Ezdro knyga",
		"Nehemijo knyga",
		"Esteros knyga",
		"Jobo knyga",
		"Psalmynas",
		"Patarlių knyga",
		"Koheleto knyga",
		"Giesmių giesmės knyga",
		"Izaijo knyga",
		"Jeremino knyga",
		"Raudų knyga",
		"Ezekielio knyga",
		"Danielio knyga",
		"Ozėjo knyga",
		"Joelio knyga",
		"Amoso knyga",
		"Abdijo knyga",
		"Jonos knyga",
		"Michėjo knyga",
		"Nahumo knyga",
		"Habakuko knyga",
		"Sofonijo knyga",
		"Agėjo knyga",
		"Zacharijo knyga",
		"Malachijo knyga",
		"Mato evangelija",
		"Morkaus evangelija",
		"Luko evangelija",
		"Jono evangelija",
		"Apaštalų darbai",
		"Laiškas romiečiams",
		"Pirmasis laiškas korintiečiams",
		"Antrasis laiškas korintiečiams",
		"Laiškas galatams",
		"Laiškas efeziečiams",
		"Laiškas filipiečiams",
		"Laiškas kolosiečiams",
		"Pirmasis laiškas tesalonikiečiams",
		"Antrasis laiškas tesalonikiečiams",
		"Pirmasis laiškas Timotiejui",
		"Antrasis laiškas Timotiejui",
		"Laiškas Titui",
		"Laiškas Filemonui",
		"Laiškas hebrajams",
		"Jokūbo laiškas",
		"Pirmasis Petro laiškas",
		"Antrasis Petro laiškas",
		"Pirmasis Jono laiškas",
		"Antrasis Jono laiškas",
		"Trečiasis Jono laiškas",
		"Judo laiškas",
		"Apreiškimas Jonui"
	};
	
	
	public static String etnames[] = {
		"Piibel",
		"väljund",
		"Peatükk",
		"raamat",
		"TESTAMENT",
		"tekst",
		"valima",
		"VANA TESTAMENT",
		"UUS TESTAMENT",
		"psalm",
		"evangeelium",
		//4 добавленных значения ниже ///////////////////////
		"Otsingu tulemused",				//<string name="findresults">
		"tikud",							//<string name="matches">
		"Luuletus",							//<string name="poem">
		"Otsi"								//<string name="searchbutton">
		};	
	
	public static String etbible[] = {
		"1. Moosese",
		"2. Moosese",
		"3. Moosese",
		"4. Moosese",
		"5. Moosese",
		"Joosua",
		"Kohtumõistjate",
		"Rutt",
		"1. Saamueli",
		"2. Saamueli",
		"1. Kuningate",
		"2. Kuningate",
		"1. Ajaraamat",
		"2. Ajaraamat",
		"Esra",
		"Nehemja",
		"Ester",
		"Iiob",
		"Laulud",
		"Õpetussõnad",
		"Koguja",
		"Ülemlaul",
		"Jesaja",
		"Jeremija",
		"Nutulaulud",
		"Hesekiel",
		"Taaniel",
		"Hoosea",
		"Joel",
		"Aamos",
		"Obadja",
		"Joona",
		"Miika",
		"Nahum",
		"Habakuk",
		"Sefanja",
		"Haggai",
		"Sakarja",
		"Malakia",
		"Matteuse",
		"Markuse",
		"Luuka",
		"Johannese",
		"Apostlite teod",
		"Roomlastele",
		"1. korintlastele",
		"2. korintlastele",
		"Galaatlastele",
		"Efeslastele",
		"Filiplastele",
		"Koloslastele",
		"1. tessalooniklastele",
		"2. tessalooniklastele",
		"1. Timoteosele",
		"2. Timoteosele",
		"Tiitusele",
		"Fileemonile",
		"Heebrealastele",
		"Jaakobuse",
		"1. Peetruse",
		"2. Peetruse",
		"1. Johannese",
		"2. Johannese",
		"3. Johannese",
		"Juuda kiri",
		"Johannese ilmutus"
	};	
	
	public static String lvnames[] = {
		"BĪBELE",
		"iziet",
		"nodaļa",
		"grāmata",
		"Derība",
		"teksts",
		"izvēlēties",
		"Vecā Derība",
		"Jaunā Derība",
		"psalms",
		"Evaņģēlijs",
		//4 добавленных значения ниже ///////////////////////
		"Meklēšanas rezultāti",				//<string name="findresults">
		"sērkociņi",						//<string name="matches">
		"Dzejolis",							//<string name="poem">
		"Meklēt"							//<string name="searchbutton">
	};	
	
	public static String lvbible[] = {
		"1. Mozus grāmata",
		"2. Mozus grāmata",
		"3. Mozus grāmata",
		"4. Mozus grāmata",
		"5. Mozus grāmata",
		"Jozuas grāmata",
		"Soģu grāmata",
		"Rutes grāmata",
		"1. Samuēla grāmata",
		"2. Samuēla grāmata",
		"1. Ķēniņu grāmata",
		"2. Ķēniņu grāmata",
		"1. Laiku grāmata",
		"2. Laiku grāmata",
		"Ezras grāmata",
		"Nehemijas grāmata",
		"Esteres grāmata",
		"Ījaba grāmata",
		"Psalmi",
		"Salamana pamācības",
		"Salamans mācītājs",
		"Salamana augstā dziesma",
		"Jesajas grāmata",
		"Jeremijas grāmata",
		"Raudu dziesmas",
		"Ecēhiēla grāmata",
		"Daniēla grāmata",
		"Hozejas grāmata",
		"Joēla grāmata",
		"Āmosa grāmata",
		"Obadijas grāmata",
		"Jonas grāmata",
		"Mihas grāmata",
		"Nahuma grāmata",
		"Habakuka grāmata",
		"Cefanijas grāmata",
		"Hagaja grāmata",
		"Caharijas grāmata",
		"Maleahija grāmata",
		"Mateja evaņģēlijs",
		"Marka evaņģēlijs",
		"Lūkas evaņģēlijs",
		"Jāņa evaņģēlijs",
		"Apustuļu darbi",
		"Romiešiem",
		"1. Korintiešiem",
		"2. Korintiešiem",
		"Galatiešiem",
		"Efeziešiem",
		"Filipiešiem",
		"Kolosiešiem",
		"1. Tesaloniķiešiem",
		"2. Tesaloniķiešiem",
		"1. Timotejam",
		"2. Timotejam",
		"Titam",
		"Filemonam",
		"Ebrejiem",
		"Jekaba vēstule",
		"Pētera 1. vēstule",
		"Pētera 2. vēstule",
		"Jāņa 1. vēstule",
		"Jāņa 2. vēstule",
		"Jāņa 3. vēstule",
		"Jūdas vēstule",
		"Atklāsmes grāmata"
	};	
	
	public static String hynames[] = {
		"ԱՍՏՈՒԱԾԱՇՈՒՆՉ",
		"արտադրանք",
		"Գլուխ",
		"գիրք",
		"ԿՏԱԿԱՐԱՆ",
		"տեքստ",
		"ընտրել",
		"ՀԻՆ ԿՏԱԿԱՐԱՆ",
		"ՆՈՐ ԿՏԱԿԱՐԱՆ",
		"սաղմոս",
		"ավետարան",
		//4 добавленных значения ниже ///////////////////////
		"Որոնման արդյունքները",				//<string name="findresults">
		"հանդիպումները",					//<string name="matches">
		"Բանաստեղծություն",					//<string name="poem">
		"գտնել"							//<string name="searchbutton">
		};
	
	
	public static String hybible[] = {
		"ԾՆՆԴՈՑ",
		"ԵԼՔ",
		"ՂԵՒՏԱԿԱՆ",
		"ԹՈՒԵՐ",
		"ԵՐԿՐՈՐԴ ՕՐէՆՔ",
		"ՅԵՍՈՒ",
		"ԴԱՏԱՒՈՐՆԵՐ",
		"ՀՌՈՒԹ",
		"ԹԱԳԱՒՈՐՈՒԹԻՒՆՆԵՐ Ա",
		"ԹԱԳԱՒՈՐՈՒԹԻՒՆՆԵՐ Բ",
		"ԹԱԳԱՒՈՐՈՒԹԻՒՆՆԵՐ Գ",
		"ԹԱԳԱՒՈՐՈՒԹԻՒՆՆԵՐ Դ",
		"Ա ՄՆԱՑՈՐԴԱՑ",
		"Բ ՄՆԱՑՈՐԴԱՑ",
		"Ա ԵԶՐԱՍ",
		"ՆԷԵՄԻ",
		"ԵՍԹԵՐ",
		"ՅՈԲ",
		"ՍԱՂՄՈՍ",
		"ԱՌԱԿՆԵՐ",
		"ԺՈՂՈՎՈՂ",
		"ԵՐԳ ԵՐԳՈՑ",
		"ԵՍԱՅԻ",
		"ԵՐԵՄԻԱ",
		"ՈՂԲ",
		"ԵԶԵԿԻԷԼ",
		"ԴԱՆԻԷԼ",
		"ՕՍԷԷ",
		"ՅՈՎԵԼ",
		"ԱՄՈՍ",
		"ԱԲԴԻՈՒ",
		"ՅՈՎՆԱՆ",
		"ՄԻՔԻԱ",
		"ՆԱՒՈՒՄ",
		"ԱՄԲԱԿՈՒՄ",
		"ՍՈՓՈՆԻԱ",
		"ԱՆԳԷ",
		"ԶԱՔԱՐԻԱ",
		"ՄԱՂԱՔԻԱ",
		"ԱՒԵՏԱՐԱՆ ԸՍՏ ՄԱՏԹԷՈՍԻ",
		"ԱՒԵՏԱՐԱՆ ԸՍՏ ՄԱՐԿՈՍՒ",
		"ԱՒԵՏԱՐԱՆ ԸՍՏ ՂՈՒԿԱՍԻ",
		"ԱՒԵՏԱՐԱՆ ԸՍՏ ՅՈՎՀԱՆՆԷՍԻ",
		"ԳՈՐԾՔ ԱՌԱՔԵԼՈՑ",
		"ՀՌՈՄԷԱՑԻՆԵՐԻՆ",
		"1 ԿՈՐՆԹԱՑԻՆԵՐԻՆ",
		"2 ԿՈՐՆԹԱՑԻՆԵՐԻՆ",
		"ԳԱՂԱՏԱՑԻՆԵՐԻՆ",
		"ԵՓԵՍԱՑԻՆԵՐ",
		"ՓԻԼԻՊԵՑԻՆԵՐ",
		"ԿՈՂՈՍԱՑԻՆԵՐ",
		"1 ԹԵՍԱՂՈՆԻԿԵՑԻՆԵՐ",
		"2 ԹԵՍԱՂՈՆԻԿԵՑԻՆԵՐ",
		"1 ՏԻՄՈԹԷՈՍ",
		"2 ՏԻՄՈԹԷՈՍ",
		"ՏԻՏՈՍ",
		"ՓԻԼԻՄՈՆ",
		"ԹՈՒՂԹ ԵԲՐԱՅԵՑԻՆԵՐԻՆ",
		"ՅԱԿՈԲՈՍ",
		"1 ՊԵՏՐՈՍ",
		"2 ՊԵՏՐՈՍ",
		"1 ՅՈՎՀԱՆՆԷՍ",
		"2 ՅՈՎՀԱՆՆԷՍ",
		"3 ՅՈՎՀԱՆՆԷՍ",
		"ՅՈՒԴԱ ԱՌԱՔԵԱԼԻ ԹՈՒՂԹԸ",
		"ՅԱՅՏՆՈՒԹԻՒՆ"
	};
	
	public static String kanames[] = {
		"ბიბლია",
		"გამომავალი",
		"თავი",
		"წიგნი",
		"აღთქმა",
		"ტექსტი",
		"შერჩევა",
		"ძველი აღთქმა",
		"ახალი აღთქმა",
		"ფსალმუნი",
		"სახარების",
		//4 добавленных значения ниже ///////////////////////
		"ძიების შედეგები",				//<string name="findresults">
		"მატჩები",					//<string name="matches">
		"პოემა",						//<string name="poem">
		"ძებნა"						//<string name="searchbutton">
		};	
	
	public static String kabible[] = {
		"დაბადება",
		"გამოსვლა",
		"ლევიანნი",
		"რიცხვნი",
		"მეორე რჯული",
		"იესო ნავეს ძე",
		"მსაჯულნი",
		"რუთი",
		"პირველი მეფეთა",
		"მეორე მეფეთა",
		"მესამე მეფეთა",
		"მეოთხე მეფეთა",
		"პირველი ნეშტთა",
		"მეორე ნეშტთა",
		"პირველი ეზრა",
		"ნეემია",
		"ესთერი",
		"იობი",
		"ფსალმუნნი",
		"იგავნი სოლომონისა",
		"ეკლესიასტე",
		"ქებათა-ქება სოლომონისა",
		"ესაია წინასწარმეტყველი",
		"იერემია წინასწარმეტყველი",
		"გოდება იერემიასი",
		"ეზეკიელ წინასწარმეტყველი",
		"დანიელ წინასწარმეტყველი",
		"ოსია წინასწარმეტყველი",
		"იოველ წინასწარმეტყველი",
		"ამოს წინასწარმეტყველი",
		"აბდია წინასწარმეტყველი",
		"იონა წინასწარმეტყველი",
		"მიქა წინასწარმეტყველი",
		"ნაუმ წინასწარმეტყველი",
		"აბაკუმ წინასწარმეტყველი",
		"სოფონია წინასწარმეტყველი",
		"ანგია წინასწარმეტყველი",
		"ზაქარია წინასწარმეტყველი",
		"მალაქია წინასწარმეტყველი",
		"მათეს სახარება",
		"მარკოზის სახარება",
		"ლუკას სახარება",
		"იოანეს სახარება",
		"მოციქულთა საქმენი",
		"იაკობის ეპისტოლე",
		"პირველი პეტრესი",
		"მეორე პეტრესი",
		"პირველი იოანესი",
		"მეორე იოანესი",
		"მესამე იოანესი",
		"იუდასი",
		"რომაელთა მიმართ",
		"პირველი კორინთელთა მიმართ",
		"მეორე კორინთელთა მიმართ",
		"გალატელთა მიმართ",
		"ეფესელთა მიმართ",
		"ფილიპელთა მიმართ",
		"კოლასელთა მიმართ",
		"პირველი თესალონიკელთა მიმართ",
		"მეორე თესალონიკელთა მიმართ",
		"პირველი ტიმოთეს მიმართ",
		"მეორე ტიმოთეს მიმართ",
		"ტიტეს მიმართ",
		"ფილიმონის მიმართ",
		"ებრაელთა მიმართ",
		"იოანეს გამოცხადება"
	};	
	
	public static String kknames[] = {
		"Киелі Кітап",
		"шығу",
		"Тарау",
		"кітап",
		"келісім",
		"мәтін",
		"таңдап алу",
		"Көне келісім",
		"Жаңа келісім",
		"діни жыр",
		"інжіл",
		//4 добавленных значения ниже ///////////////////////
		"Ізденістің нәтижелері",		//<string name="findresults">
		"түйіс-",						//<string name="matches">
		"тынымдады",					//<string name="poem">
		"іздеу"							//<string name="searchbutton">
	};	
	
	public static String kkbible[] = {
		"Жаратылыстың басталуы",
		"Мысырдан көшіп шығу",
		"Леуіліктер",
		"Руларды санау",
		"Заңды қайталау",
		"Ешуа",
		"Билер",
		"Рут",
		"Патшалықтар туралы 1-ші жазба",
		"Патшалықтар туралы 2-ші жазба",
		"Патшалықтар туралы 3-ші жазба",
		"Патшалықтар туралы 4-ші жазба",
		"Шежірелердің 1-ші жазбасы",
		"Шежірелердің 2-ші жазбасы",
		"Езра",
		"Нехемия",
		"Естер",
		"Әйүп",
		"Забур жырлары",
		"Нақыл сөздер",
		"Уағыздаушы",
		"Сүлейменнің таңдаулы әні",
		"Ишая",
		"Еремия",
		"Жоқтау",
		"Езекиел",
		"Даниял",
		"Ошия",
		"Жоел",
		"Амос",
		"Абди",
		"Жүніс",
		"Миха",
		"Нахум",
		"Хабаққұқ",
		"Софония",
		"Хаггай",
		"Зәкәрия",
		"Малахия",
		"Матай ізгі хабары",
		"Марқа ізгі хабары",
		"Лұқа ізгі хабары",
		"Жохан ізгі хабары",
		"Елшілердің істері",
		"Римдіктерге арналған хат",
		"Қорынттықтарға арналған 1-ші хат",
		"Қорынттықтарға арналған 2-ші хат",
		"Ғалаттықтарға арналған хат",
		"Ефестіктерге арналған хат",
		"Філіпіліктерге арналған хат",
		"Қолостықтарға арналған хат",
		"Салоникалықтарға арналған 1-ші хат",
		"Салоникалықтарға арналған 2-ші хат",
		"Тімотеге арналған 1-ші хат",
		"Тімотеге арналған 2-ші хат",
		"Титке арналған хат",
		"Філимонға арналған хат",
		"Еврейлерге арналған хат",
		"Жақыптың хаты",
		"Петірдің 1-ші хаты",
		"Петірдің 2-ші хаты",
		"Жоханның 1-ші хаты",
		"Жоханның 2-ші хаты",
		"Жоханның 3-ші хаты",
		"Яһуданың хаты",
		"Жохан аяны"
	};	
	
	public static String hrnames[] = {
		"Biblija",
		"izlaz",
		"Poglavlje",
		"Knjiga",
		"Zavjet",
		"Tekst",
		"Odaberi",
		"Stari zavjet",
		"Novi zavjet",
		"Psalam",
		"Evanđelje",
		//4 добавленных значения ниже ///////////////////////
		"Traženi Rezultati",		//<string name="findresults">
		"šibice",					//<string name="matches">
		"Pjesma",					//<string name="poem">
		"Pronađi"					//<string name="searchbutton">
		};	
	
	public static String hrbible[] = {
		"Postanak",
		"Izlazak",
		"Levitski zakonik",
		"Brojevi",
		"Ponovljeni zakon",
		"Jošua",
		"Suci",
		"Ruta",
		"1 Samuelova",
		"2 Samuelova",
		"1 Kraljevima",
		"2 Kraljevima",
		"1 Ljetopisa",
		"2 Ljetopisa",
		"Ezra",
		"Nehemija",
		"Estera",
		"Job",
		"Psalmi",
		"Mudre Izreke",
		"Propovjednik",
		"Pjesma nad Pjesmama",
		"Izaija",
		"Jeremija",
		"Tužaljke",
		"Ezekiel",
		"Daniel",
		"Hošea",
		"Joel",
		"Amos",
		"Obadija",
		"Jona",
		"Mihej",
		"Nahum",
		"Habakuk",
		"Sefanija",
		"Hagaj",
		"Zaharija",
		"Malahija",
		"Matej",
		"Marko",
		"Luka",
		"Ivan",
		"Djela apostolska",
		"Rimljanima",
		"1 Korinčanima",
		"2 Korinčanima",
		"Galačanima",
		"Efežanima",
		"Filipljanima",
		"Kološanima",
		"1 Solunjanima",
		"2 Solunjanima",
		"1 Timoteju",
		"2 Timoteju",
		"Titu",
		"Filemonu",
		"Jevrejima",
		"Jakovljeva",
		"1 Petrova",
		"2 Petrova",
		"1 Ivanova",
		"2 Ivanova",
		"3 Ivanova",
		"Judina",
		"Otkrivenje"
	};	
	
	public static String bgnames[] = {
		"Библия",
		"Излизане",
		"Глава",
		"Книга",
		"Завет",
		"Текст",
		"Избор",
		"Стар Завет",
		"Нов Завет",
		"псалм",
		"Евангелие",
		//4 добавленных значения ниже ///////////////////////
		"Резултати от търсенето",		//<string name="findresults">
		"Кибрит",						//<string name="matches">
		"стих",							//<string name="poem">
		"Намирам"						//<string name="searchbutton">
		};	
	
	public static String bgbible[] = {
		"Битие",
		"Изход",
		"Левит",
		"Числа",
		"Второзаконие",
		"Исус Навиев",
		"Съдии",
		"Рут",
		"1 Царе",
		"2 Царе",
		"3 Царе",
		"4 Царе",
		"1 Летописи",
		"2 Летописи",
		"Ездра",
		"Неемия",
		"Естир",
		"Йов",
		"Псалми",
		"Притчи",
		"Еклесиаст",
		"Песен на песните",
		"Исая",
		"Еремия",
		"Плач Еремиев",
		"Езекил",
		"Данаил",
		"Осия",
		"Иоил",
		"Амос",
		"Авдий",
		"Йон",
		"Михей",
		"Наум",
		"Авакум",
		"Софоний",
		"Агей",
		"Захария",
		"Малахия",
		"Матей",
		"Марко",
		"Лука",
		"Йоан",
		"Деяния",
		"Римляни",
		"1 Коринтяни",
		"2 Коринтяни",
		"Галатяни",
		"Ефесяни",
		"Филипяни",
		"Колосяни",
		"1 Солунци",
		"2 Солунци",
		"1 Тимотей",
		"2 Тимотей",
		"Тит",
		"Филимон",
		"Евреи",
		"Яков",
		"1 Петрово",
		"2 Петрово",
		"1 Йоаново",
		"2 Йоаново",
		"3 Йоаново",
		"Юда",
		"Откровение"
	};	
	
	public static String uknames[] = {
		"Біблія",
		"вихід",
		"глава",
		"книга",
		"заповіт",
		"текст",
		"вибрати",
		"Старий заповіт",
		"Новий заповіт",
		"псалом",
		"Євангеліє",
		//4 добавленных значения ниже ///////////////////////
		"Результати пошуку",			//<string name="findresults">
		"збігів",						//<string name="matches">
		"вірш",							//<string name="poem">
		"Знайти"						//<string name="searchbutton">
		};	
	
	public static String ukbible[] = {
		"Буття",
		"Вихід",
		"Левит",
		"Числа",
		"Повторення Закону",
		"Ісус Навин",
		"Книга Суддів",
		"Рут",
		"1 Самуїлова",
		"2 Самуїлова",
		"1 Царів",
		"2 Царів",
		"1 Хроніки",
		"2 Хроніки",
		"Ездра",
		"Неемія",
		"Естер",
		"Йов",
		"Псалми",
		"Приповісті",
		"Екклезіяст",
		"Пісня над піснями",
		"Ісая",
		"Єремія",
		"Плач Єремії",
		"Єзекіїль",
		"Даниїл",
		"Осія",
		"Йоїл",
		"Амос",
		"Овдій",
		"Йона",
		"Михей",
		"Наум",
		"Авакум",
		"Софонія",
		"Огій",
		"Захарія",
		"Малахії",
		"Від Матвія",
		"Від Марка",
		"Від Луки",
		"Від Івана",
		"Дії Апостолі",
		"Якова",
		"1 Петра",
		"2 Петра",
		"1 Івана",
		"2 Івана",
		"3 Івана",
		"Юда",
		"До Римлян",
		"1 до Коринтян",
		"2 до Коринтян",
		"До Галатів",
		"До Ефесян",
		"До филип'ян",
		"До Колоссян",
		"1 до Солунян",
		"2 до Солунян",
		"1 Тимофію",
		"2 Тимофію",
		"До Тита",
		"До Филимона",
		"До Євреїв",
		"Об'явлення"
	};	
	
	public static String benames[] = {
		"Біблія",
		"выхад",
		"Разьдзел",
		"Кніга",
		"ЗАПАВЕТ",
		"тэкст",
		"выбраць",
		"СТАРЫ ЗАПАВЕТ",
		"НОВЫ ЗАПАВЕТ",
		"псальма",
		"Евангелле",
		//4 добавленных значения ниже ///////////////////////
		"Вынікі пошуку",					//<string name="findresults">
		"супадзенняў",						//<string name="matches">
		"верш",								//<string name="poem">
		"Пошук"								//<string name="searchbutton">
		};	
	
	public static String bebible[] = {
		"Быцьцё",
		"Выхад",
		"Лявіт",
		"Лікі",
		"Другі закон",
		"Кніга Ісуса сына Нава",
		"Кніга Судзьдзяў",
		"Кніга Рут",
		"Першая кніга Царстваў",
		"Другая кніга Царстваў",
		"Трэйцяя кніга Царстваў",
		"Чацьвёртая кніга Царстваў",
		"Першая кніга Летапісаў",
		"Другая кніга Летапісаў",
		"Кніга Эздры",
		"Кніга Нээміі",
		"Кніга Эстэр",
		"Кніга Ёва",
		"Псалтыр",
		"Кніга Выслоўяў Саламонавых",
		"Кніга Эклезіяста, альбо Прапаведніка",
		"Найвышэйшая Песьня Саламонава",
		"Кніга Прарока Ісаі",
		"Кніга Прарока Ераміі",
		"Ераміін Плач",
		"Кніга Прарока Езэкііля",
		"Кніга Прарока Данііла",
		"Кніга Асіі",
		"Кніга Ёіля",
		"Кніга Амоса",
		"Кніга Аўдзея",
		"Кніга Ёны",
		"Кніга Міхея",
		"Кніга Навума",
		"Кніга Абакума",
		"Кніга Сафона",
		"Кніга Агея",
		"Кніга Захарыі",
		"Кніга Малахіі",
		"Паводле Мацьвея Сьвятое Дабравесьце",
		"Паводле Марка Сьвятое Дабравесьце",
		"Паводле Лукаша Сьвятое Дабравесьце",
		"Паводле Яна Сьвятое Дабравесьце",
		"Дзеі Сьвятых Апосталаў",
		"Саборнае Пасланьне Сьвятога Апостала Якава",
		"Першае Саборнае Пасланьне Сьвятога Апостала Пятра",
		"Другое Саборнае Пасланьне Сьвятога Апостала Пятра",
		"Першае Саборнае Пасланьне Сьвятога Апостала Яна Багаслова",
		"Другое Саборнае Пасланьне Сьвятога Апостала Яна Багаслова",
		"Трэйцяе Саборнае Пасланьне Сьвятога Апостала Яна Багаслова",
		"Саборнае Пасланьне Сьвятога Апостала Юды",
		"Пасланьне Да Рымлянаў Сьвятога Апостала Паўла",
		"Першае Пасланьне Да Карынфянаў Сьвятога Апостала Паўла",
		"Другое Пасланьне Да Карынфянаў Сьвятога Апостала Паўла",
		"Пасланьне Да Галятаў Сьвятога Апостала Паўла",
		"Пасланьне Да Эфэсянаў Сьвятога Апостала Паўла",
		"Пасланьне Да Піліпянаў Сьвятога Апостала Паўла",
		"Пасланьне Да Каласянаў Сьвятога Апостала Паўла",
		"Першае Пасланьне Да Фесаланікійцаў Сьвятога Апостала Паўла",
		"Другое Пасланьне Да Фесаланікійцаў Сьвятога Апостала Паўла",
		"Першае Пасланьне Да Цімафея Сьвятога Апостала Паўла",
		"Другое Пасланьне Да Цімафея Сьвятога Апостала Паўла",
		"Пасланьне Да Ціта Сьвятога Апостала Паўла",
		"Пасланьне Да Філімона Сьвятога Апостала Паўла",
		"Пасланьне Да Габрэяў Сьвятога Апостала Паўла",
		"Адкрыцьцё (Апакаліпсіс) Сьвятога Апостала Яна Багаслова"
	};	
	
	public static String sqnames[] = {
		"Bibla e Shenjtë",
		"dalje",
		"kapitull",
		"libër",
		"testament",
		"text",
		"zgjedhin",
		"Dhjata e Vjetër",
		"Dhjata e Re",
		"PSALMI",
		"Ungjilli",
		//4 добавленных значения ниже ///////////////////////
		"Gjej rezultatet",					//<string name="findresults">
		"shkrepëse",						//<string name="matches">
		"Poemë",							//<string name="poem">
		"Gjej"								//<string name="searchbutton">
		};	
	
	public static String sqbible[] = {
		"Zanafilla",
		"Eksodi",
		"Levítivo",
		"Ligji I Përtërirë",
		"Ligji I Përtërirë",
		"Jozueu",
		"Gjyqtarët",
		"Ruthi",
		"I I Samuelit",
		"Ii I Samuelit",
		"1 I Mbretërve",
		"2 I Mbretërve",
		"I I Kronikave",
		"Ii I Kronikave",
		"Esdra",
		"Nehemia",
		"Ester",
		"Jobi",
		"Psalmet",
		"Fjalët E Urta",
		"Predikuesi",
		"Kantiku I Kantikëve",
		"Isaia",
		"Jeremia",
		"Vajtimet",
		"Ezekieli",
		"Danieli",
		"Osea",
		"Joeli",
		"Amosi",
		"Abdia",
		"Jona",
		"Mikea",
		"Nahumi",
		"Habakuku",
		"Sofonia",
		"Hagai",
		"Zakaria",
		"Malakia",
		"Mateu",
		"Marku",
		"Lluka",
		"Gjoni",
		"Veprat",
		"Romakeve",
		"I Korintasve",
		"Ii Korintasve",
		"Galatasve",
		"Efesianeve",
		"Filipianeve",
		"Kolosianeve",
		"I Selanikasve",
		"Ii Selanikasve",
		"I Timoteut",
		"Ii Timoteut",
		"Titit",
		"Filemonit",
		"Hebrenjte",
		"Jakobi",
		"Pjetri",
		"Pjetri",
		"I Gjoni",
		"Ii Gjoni",
		"Iii Gjoni",
		"Juda",
		"Zbulesa"
	};
	
	public static String csnames[] = {
		"Bible",
		"exit",
		"kapitola",
		"kniha",
		"závěť",
		"text",
		"vybrat",
		"Starý zákon",
		"Nový zákon",
		"Žalm",
		"Evangelium",
		//4 добавленных значения ниже ///////////////////////
		"Výsledky vyhledávání",			//<string name="findresults">
		"Zápalky",						//<string name="matches">
		"Báseň",						//<string name="poem">
		"Najít"							//<string name="searchbutton">
		};	
	
	public static String csbible[] = {
		"1. Mojžišova",
		"2. Mojžišova",
		"3. Mojžišova",
		"4. Mojžišova",
		"5. Mojžišova",
		"Józua",
		"Sudcov",
		"Rút",
		"1. Samuelova",
		"2. Samuelova",
		"1. Krá¾ov",
		"2. Krá¾ov",
		"1. Kronická",
		"2. Kronická",
		"Ezdráš",
		"Nehemiáš",
		"Ester",
		"Jób",
		"Žalmy",
		"Príslovia",
		"Kazate¾",
		"Pieseò",
		"Izaiáš",
		"Jeremiáš",
		"Plaè",
		"Ezechiel",
		"Daniel",
		"Hozeáš",
		"Joel",
		"Ámos",
		"Obadiáš",
		"Jonáš",
		"Micheáš",
		"Náhum",
		"Habakuk",
		"Sofoniáš",
		"Haggeus",
		"Zachariáš",
		"Malachiáš",
		"Matouš",
		"Marek",
		"Lukáš",
		"Jan",
		"Skutky Apoštolů",
		"Římanům",
		"1 Korintským",
		"2 Korintským",
		"Galatským",
		"Efezským",
		"Filipským",
		"Koloským",
		"1 Tesalonickým",
		"2 Tesalonickým",
		"1 Timoteovi",
		"2 Timoteovi",
		"Titovi",
		"Filemonovi",
		"Židům",
		"Jakubův",
		"1 Petrův",
		"2 Petrův",
		"1 Janův",
		"2 Janův",
		"3 Janův",
		"Judův",
		"Zjevení Janovo"
	};
	
	public static String finames[] = {
		"Raamattu",
		"exit",
		"luku",
		"kirja",
		"testamentti",
		"text",
		"valita",
		"Vanha testamentti",
		"Uusi testamentti",
		"PSALM",
		"Gospel",
		//4 добавленных значения ниже ///////////////////////
		"Hae tulokset",				//<string name="findresults">
		"tulitikut",				//<string name="matches">
		"Runo",						//<string name="poem">
		"haku"						//<string name="searchbutton">
		};	
	
	public static String fibible[] = {
		"Ensimmäinen Mooseksen",
		"Toinen Mooseksen",
		"Kolmas Mooseksen",
		"Neljäs Mooseksen",
		"Viides Mooseksen",
		"Joosua",
		"Tuomarien Kirja",
		"Ruut",
		"Ensimmäinen Samuelin Kirja",
		"Toinen Samuelin Kirja",
		"Ensimmäinen Kuningasten Kirja",
		"Toinen Kuningasten Kirja",
		"Ensimmäinen Aikakirja",
		"Toinen Aikakirja",
		"Esra",
		"Nehemia",
		"Ester",
		"Job",
		"Psalmit",
		"Sananlaskut",
		"Saarnaaja",
		"Korkea Veisu",
		"Jesaja",
		"Jeremia",
		"Valitusvirret",
		"Hesekiel",
		"Daniel",
		"Hoosea",
		"Jooel",
		"Aamos",
		"Obadja",
		"Joona",
		"Miika",
		"Naahum",
		"Habakuk",
		"Sefanja",
		"Haggai",
		"Sakarja",
		"Malakia",
		"Matteuksen",
		"Markuksen",
		"Luukkaan",
		"Johanneksen",
		"Apostolien teot",
		"Kirje roomalaisille",
		"Ensimmäinen kirje korinttilaisille",
		"Toinen kirje korinttilaisille",
		"Kirje galatalaisille",
		"Kirje efesolaisille",
		"Kirje filippiläisille",
		"Kirje kolossalaisille",
		"Ensimmäinen kirje tessalonikalaisille",
		"Toinen kirje tessalonikalaisille",
		"Ensimmäinen kirje Timoteukselle",
		"Toinen kirje Timoteukselle",
		"Kirje Titukselle",
		"Kirje Filemonille",
		"Kirje heprealaisille",
		"Jaakobin kirje",
		"Ensimmäinen Pietarin kirje",
		"Toinen Pietarin kirje",
		"Ensimmäinen Johanneksen kirje",
		"Toinen Johanneksen kirje",
		"Kolmas Johanneksen kirje",
		"Juudaksen kirje",
		"Johanneksen ilmestys"
	};
	
	public static String nonames[] = {
		"Bibelen",
		"exit",
		"kapittel",
		"bok",
		"testament",
		"tekst",
		"velg",
		"Det gamle testamente",
		"Det nye testamente",
		"Salme",
		"Gospel",
		//4 добавленных значения ниже ///////////////////////
		"Søkeresultater",			//<string name="findresults">
		"fyrstikker",				//<string name="matches">
		"Dikt",						//<string name="poem">
		"finne"						//<string name="searchbutton">
		};	
	
	public static String nobible[] = {
		"1 Mosebok",
		"2 Mosebok",
		"3 Mosebok",
		"4 Mosebok",
		"5 Mosebok",
		"Josvas",
		"Dommernes",
		"Ruts",
		"1 Samuels",
		"2 Samuel",
		"Første Kongebok",
		"Anden Kongebok",
		"Første Krønikebok",
		"Anden Krønikebok",
		"Esras",
		"Nehemias",
		"Esters",
		"Jobs",
		"Salmenes",
		"Salomos Ordsprog",
		"Predikerens",
		"Salomos Høisang",
		"Esaias",
		"Jeremias",
		"Klagesangene",
		"Esekiel",
		"Daniel",
		"Hoseas",
		"Joel",
		"Amos",
		"Obadias",
		"Jonas",
		"Mika",
		"Nahum",
		"Habakuk",
		"Sefanias",
		"Haggai",
		"Sakarias",
		"Malakias",
		"Matteus",
		"Markus",
		"Lukas",
		"Johannes",
		"Apostlenes-gjerninge",
		"Romerne",
		"1 Korintierne",
		"2 Korintierne",
		"Galaterne",
		"Efeserne",
		"Filippenserne",
		"Kolossenserne",
		"1 Tessalonikerne",
		"2 Tessalonikerne",
		"1 Timoteus",
		"2 Timoteus",
		"Titus",
		"Filemon",
		"Hebreerne",
		"Jakobs",
		"1 Peters",
		"2 Peters",
		"1 Johannes",
		"2 Johannes",
		"3 Johannes",
		"Judas",
		"Apenbaring"
	};
	
	public static String svnames[] = {
		"BIBELN",
		"avsluta",
		"kapitel",
		"bok",
		"testamente",
		"text",
		"välja",
		"Det Gamle Testamente",
		"Det Nye Testamente",
		"PSALM",
		"Gospel",
		"Sökresultat",				//<string name="findresults">
		"Resultat",					//<string name="matches">
		"Poem",						//<string name="poem">
		"Sök"						//<string name="searchbutton">
		};	
	
	public static String svbible[] = {
		"1 Mosebok",
		"2 Mosebok",
		"3 Mosebok",
		"4 Mosebok",
		"5 Mosebok",
		"Josuaé",
		"Domarboken",
		"Rut",
		"1 Samuelsboken",
		"2 Samuelsbokem",
		"1 Kungaboken",
		"2 Kungaboken",
		"1 Krönikeboken",
		"2 Krönikeboken",
		"Esra",
		"Nehemja",
		"Ester",
		"Job",
		"Psaltaren",
		"Ordspråksboken",
		"Predikaren",
		"Hga Visan",
		"Jesaja",
		"Jeremia",
		"Klagovisorna",
		"Hesekiel",
		"Daniel",
		"Hosea",
		"Joel",
		"Amos",
		"Obadja",
		"Jona",
		"Mika",
		"Nahum",
		"Habackuk",
		"Sefanja",
		"Haggai",
		"Sakaria",
		"Malaki",
		"Matteus",
		"Markus",
		"Lukas",
		"Johannes",
		"Apostagärningarna",
		"Romabrevet",
		"1 Korinthierbrevet",
		"2 Korinthierbrevet",
		"Galaterbrevet",
		"Efesierbrevet",
		"Filipperbrevet",
		"Kolosserbrevet",
		"1 Thessalonikerbr.",
		"2 Thessalonikerbr.",
		"1 Timotheosbrevet",
		"2 Timotheosbrevet",
		"Titusbrevet",
		"Filemonbrevet",
		"Hebreerbrevet",
		"Jakobsbrevet",
		"1 Petrusbrevet",
		"2 Petrusbrevet",
		"1 Johannesbrevet",
		"2 Johannesbrevet",
		"3 Johannesbrevet",
		"Judasbrevet",
		"Uppenbarelseboken"
	};
	
	
	public static String bnnames[] = {
		"পবিত্র বাইবেল",
		"প্রস্থান",
		"অধ্যায়",
		"বই",
		"উইল",
		"পাঠ",
		"নির্বাচন করা",
		"পুরানো ইচ্ছাপত্র",
		"নববিধান",
		"স্তব",
		"ধর্মবাণী",
		"অনুসন্ধান ফলাফল",				//<string name="findresults">
		"ম্যাচ",						//<string name="matches">
		"কবিতা",						//<string name="poem">
		"খুঁজুন"						//<string name="searchbutton">
		};	
	
	public static String bnbible[] = {
		"আদিপুস্তক",
		"যাত্রাপুস্তক",
		"লেবীয় পুস্তক",
		"গণনা পুস্তক",
		"দ্বিতীয় বিবরণ",
		"যোশুয়া",
		"বিচারকচরিত",
		"রুথ",
		"সামুয়েল ১",
		"সামুয়েল ২",
		"রাজাবলি ১",
		"রাজাবলি ২",
		"বংশাবলি ১",
		"বংশাবলি ২",
		"এজরা",
		"নেহেমিয়া",
		"এস্থার",
		"যোব",
		"সামসঙ্গীত",
		"প্রবচন",
		"উপদেশক",
		"পরম গীত",
		"ইসাইয়া",
		"যেরেমিয়া",
		"বিলাপ-গাথা",
		"এজেকিয়েল",
		"দানিয়েল",
		"হোসেয়া",
		"যোয়েল",
		"আমোস",
		"ওবাদিয়া",
		"যোনা",
		"মিখা",
		"নাহুম",
		"হাবাকুক",
		"জেফানিয়া",
		"হগয়",
		"জাখারিয়া",
		"মালাখি",
		"মথি",
		"মার্ক",
		"লুক",
		"যোহন",
		"पশিষ্যচরিত",
		"রোমীয়",
		"করিন্থীয় ১",
		"করিন্থীয় ২",
		"গালাতীয়",
		"এফেসীয়",
		"ফিলিপ্পীয়",
		"কলসীয়",
		"থেসালোনিকীয় ১",
		"থেসালোনিকীয় ২",
		"তিমথি ১",
		"তিমথি ২",
		"তীত",
		"ফিলেমন",
		"হিব্রুদের কাছে পত্র",
		"যাকোবের পত্র",
		"পিতরের ১ম পত্র",
		"পিতরের ২য় পত্র",
		"যোহনের ১ম পত্র",
		"যোহনের ২য় পত্",
		"যোহনের ৩য় পত্",
		"যুদের পত্র",
		"पপ্রত্যাদেশ"
	};	
	
	public static String fanames[] = {
		"کتاب مقدس",
		"خروج",
		"فصل",
		"کتاب",
		"وصیتنامه",
		"متن",
		"را انتخاب کنید",
		"عهد قديم",
		"عهد جديد",
		"مزمور",
		"مزمور",
		"نتایج جستجو",					//<string name="findresults">
		"کبریت",						//<string name="matches">
		"شعر",						//<string name="poem">
		"جستجو"						//<string name="searchbutton">
		};	
	
	public static String fabible[] = {	
	
	"پيدايش",
	"سفر خروج",
	"لاويان",
	"اعداد",
	"تثنييه",
	"يشوع",
	"داوران",
	"روت",
	"اول سموئيل",
	"دوم سموئيل",
	"اول پادشاهان",
	"دوم پادشاهان",
	"اول تواريخ",
	"دوم تواريخ",
	"عزرا",
	"نحيميا",
	"استر",
	"ايوب",
	"مزامير",
	"امثال",
	"جامعه",
	"غزلی از غزلها",
	"اشعيا",
	"ارمييا",
	"نوحه",
	"حزقيال",
	"دانيال",
	"هوزيا",
	"يوئيل",
	"عاموس",
	"عوبيديا",
	"يونس",
	"ميکاه",
	"ناحوم",
	"حبقوق",
	"ضفينيا",
	"حجی",
	"زکريا",
	"ملاکی",
	"متی",
	"مرقس",
	"لوقا",
	"يوحنا",
	"اعمال رسولان",
	"روميان",
	"اول قرنتيان",
	"دوم قرنتيان",
	"غلاطيان",
	"افسسيان",
	"فيليپيان",
	"کولوسيان",
	"اول تسالونيکيان",
	"دوم تسالونيکيان",
	"اول تيموتيوس",
	"دوم تيموتيوس",
	"تايتوس",
	"فيلمان",
	"عبرانيان",
	"يعقوب",
	"اول پترس",
	"دوم پترس",
	"اول يوحنا",
	"دوم يوحنا",
	"سوم يوحنا",
	"يهودا",
	"مکاشفه"	
	};	
	
	public static String urnames[] = {
		"انجیل مقدس",
		"سے باہر نکلنے کے",
		"باب",
		"کتاب",
		"عہد نامہ",
		"متن",
		"کا انتخاب",
		"پرانے عہد نامہ",
		"نئے عہد نامہ",
		"زبور",
		"انجیل",
		"نتائجِ‌تلاش",					//<string name="findresults">
		"میچ",						//<string name="matches">
		"نظم",						//<string name="poem">
		"تلاش"						//<string name="searchbutton">
		};	

	public static String urbible[] = {	
		"پَیدایش",
		"خُرُوج",
		"احبار",
		"گِنتی",
		"اِستِثنا",
		"یشُوع",
		"قُضاۃ",
		"رُوت",
		"۱-سموئیل",
		"۲-سموئیل",
		"۱-سلاطِین",
		"۲-سلاطِین",
		"۱-توارِیخ",
		"۲- توارِیخ",
		"عزرا",
		"نحمیاہ",
		"آستر",
		"ایُّوب",
		"زبُو",
		"امثال",
		"واعِظ",
		"غزلُ الغزلات",
		"یسعیاہ",
		"یرمِیاہ",
		"نَوحہ",
		"حِزقی ایل",
		"دانی ایل",
		"ہوسیعَِ",
		"یُوایل",
		"عامُوس",
		"عبدیاہ",
		"یُوناہ",
		"مِیکاہ",
		"ناحُوم",
		"حبقُّوق",
		"صفنیاہ",
		"حجَّی",
		"زکریاہ",
		"ملاکی",
		"متّی",
		"مرقس",
		"لُوقا",
		"یُوحنّا",
		"اَعمال",
		"رُومِیوں",
		"۱-کُرِنتھِیوں",
		"۲-کُرِنتھِیوں",
		"گلتِیوں",
		"اِفسِیوں",
		"فِلپّیوں",
		"کُلسِیوں",
		"۱-تھِسّلُنیکیوں",
		"۲-تھِسّلُنیکیوں",
		"۱-تِیمُتھِیُس",
		"۲-تِیمُتھِیُس",
		"طِطُس",
		"فِلیمون",
		"عِبرانیوں",
		"یعقُوب",
		"۱-پطرس",
		"۲-پطرس",
		"۱-یُوحنّا",
		"۲-یُوحنّا",
		"۳-یُوحنّا",
		"یہُوداہ",
		"مُکاشفہ"
	};	
	
	public static String ronames[] = {
		"Biblia",
		"ieșire",
		"Capitolul",
		"carte",
		"testament",
		"text",
		"alege",
		"Vechiul Testament",
		"Noul Testament",
		"PSALM",
		"Evanghelia",
		"Caută cuvinte",				//<string name="findresults">
		"meciuri",						//<string name="matches">
		"Poezie",						//<string name="poem">
		"găsi"							//<string name="searchbutton">
		};

		public static String robible[] = {
		"Facerea",
		"Ieşirea",
		"Levitic",
		"Numeri",
		"Deuteronom",
		"Iosua",
		"Judecători",
		"Rut",
		"1 Samuel",
		"2 Samuel",
		"1 Regi",
		"2 Regi",
		"1 Cronici",
		"2 Cronici",
		"Ezra",
		"Neemia",
		"Estera",
		"Iov",
		"Psalmi",
		"Proverbe",
		"Ecleziast",
		"Cântarea Cântărilor",
		"Isaia",
		"Ieremia",
		"Plângerile lui Ieremia",
		"Ezechiel",
		"Daniel",
		"Osea",
		"Ioel",
		"Amos",
		"Obadia",
		"Iona",
		"Mica",
		"Naum",
		"Habacuc",
		"Ţefania",
		"Hagai",
		"Zaharia",
		"Maleahi",
		"Matei",
		"Marcu",
		"Luca",
		"Ioan",
		"Faptele Apostolilor",
		"Romani",
		"1 Corinteni",
		"2 Corinteni",
		"Galateni",
		"Efeseni",
		"Filipeni",
		"Coloseni",
		"1 Tesaloniceni",
		"2 Tesaloniceni",
		"1 Timotei",
		"2 Timotei",
		"Tit",
		"Filimon",
		"Evrei",
		"Iacob",
		"1 Petru",
		"2 Petru",
		"1 Ioan",
		"2 Ioan",
		"3 Ioan",
		"Iuda",
		"Apocalipsa"
		};
	
	
	public static String danames[] = {
		"Bibelen",
		"afslutte",
		"Kapitel",
		"Bog",
		"Det Nye Testamente",
		"tekst",
		"vælge",
		"Det Gamle Testamente",
		"Det Nye Testamente",
		"salme",
		"evangeliet",
		//4 добавленных значения ниже ///////////////////////
		"Søgeresultater",				//<string name="findresults">
		"Tændstikker",					//<string name="matches">
		"Digt",							//<string name="poem">
		"Søg"							//<string name="searchbutton">
		};

		public static String dabible[] = {
		"1 Mosebog",
		"2 Mosebog",
		"3 Mosebog",
		"4 Mosebog",
		"5 Mosebog",
		"Josua",
		"Dommer",
		"Rut",
		"1 Samuel",
		"2 Samuel",
		"Første Kongebog",
		"Anden Kongebog",
		"Første Krønikebog",
		"Anden Krønikebog",
		"Ezra",
		"Nehemias",
		"Ester",
		"Job",
		"Salme",
		"Ordsprogene",
		"Prædikeren",
		"Højsangen",
		"Esajas",
		"Jeremias",
		"Klagesangene",
		"Ezekiel",
		"Daniel",
		"Hoseas",
		"Joel",
		"Amos",
		"Obadias",
		"Jonas",
		"Mikas",
		"Nahum",
		"Habakkuk",
		"Zefanias",
		"Haggaj",
		"Zakarias",
		"Malakias",
		"Matthæus",
		"Markus",
		"Lukas",
		"Johannes",
		"Apostelenes gerninger",
		"Romerne",
		"1 Korinterne",
		"2 Korinterne",
		"Galaterne",
		"Efeserne",
		"Filipperne",
		"Kolossensern",
		"1 Tessalonikerne",
		"2 Tessalonikerne",
		"1 Timoteus",
		"2 Timoteus",
		"Titus",
		"Filemon",
		"Hebræerne",
		"Jakob",
		"1 Peter",
		"2 Peter",
		"1 Johannes",
		"2 Johannes",
		"3 Johannes",
		"Judas",
		"Aabenbaringen"

		};	
	
	public static String thnames[] = {
		"คัมภีร์ไบเบิล",
		"ทางออก",
		"บท",
		"หนังสือ",
		"พินัยกรรม",
		"ข้อความ",
		"เลือก",
		"พันธสัญญาเดิม",
		"พันธสัญญาใหม่",
		"สดุดี",
		"พระเยซู",
		//4 добавленных значения ниже ///////////////////////
		"ผลลัพธ์การค้นหา",						//<string name="findresults">
		"ไม้ขีด",							//<string name="matches">
		"บทกวี",							//<string name="poem">
		"หา"								//<string name="searchbutton">
		};	
			
		public static String thbible[] = {
			"ปฐมกาล",
			"อพยพ",
			"เลวีนิติ ",
			"กันดารวิถี",
			"เฉลยธรมบัญญัติ",
			"โยชูวา",
			"ผู้วินิจฉัย ",
			"นางรูธ ",
			"1 ซามูเอล ",
			"2 ซามูเอล ",
			"1 พงศ์กษัตริย์ ",
			"2 พงศ์กษัตริย์ ",
			"1 พงศาวดาร",
			"2 พงศาวดาร ",
			"เอสรา ",
			"เนหะมีย์ ",
			"เอสเธอร์",
			"โยบ",
			"สดุดี ",
			"สุภาษิต ",
			"ปัญญาจารย์ ",
			"เพลงซาโลมอน",
			"อิสยาห์ ",
			"เยเรมีย์",
			"เพลงคร่ำครวญ ",
			"เอเสเคียล",
			"ดาเนียล",
			"โฮเชยา",
			"โยเอล",
			"อาโมส",
			"โอบาดีย์",
			"โยนาห์",
			"มีคาห์",
			"นาฮูม",
			"ฮะบากุก",
			"เศฟันยาห์",
			"ฮักกัย",
			"เศคาริยาห์",
			"มาลาคี",
			"มัทธิว ",
			"มาระโก ",
			"ลูกา ",
			"ยอห์น ",
			"กิจการของอัครทูต",
			"โรม ",
			"1 โครินธ์ ",
			"2 โครินธ์ ",
			"กาลาเทีย ",
			"เอเฟซัส ",
			"ฟิลิปปี ",
			"โคโลสี ",
			"1 เธสะโลนิกา ",
			"2 เธสะโลนิกา ",
			"1 ทิโมธี ",
			"2 ทิโมธี ",
			"ทิตัส ",
			"ฟีเลโมน",
			"ฮีบรู ",
			"ยากอบ ",
			"1 เปโตร ",
			"2 เปโตร ",
			"1 ยอห์น ",
			"2 ยอห์น ",
			"3 ยอห์น ",
			"ยูดา",
			"วิวรณ์"
		};	
	
	public static String hunames[] = {
		"Szent Biblia",
		"kilépés",
		"fejezet",
		"könyv",
		"végrendelet",
		"szöveg",
		"választ",
		"Ószövetség",
		"Újszövetség",
		"zsoltár",
		"evangélium",
		//4 добавленных значения ниже ///////////////////////
		"Keresés eredménye",					//<string name="findresults">
		"eredménnyel",							//<string name="matches">
		"Vers",									//<string name="poem">
		"talál"									//<string name="searchbutton">
		};

		public static String hubible[] = {
		"Mózes első könyve",
		"Mózes második könyve",
		"Mózes harmadik könyve",
		"Mózes negyedik könyve",
		"Mózes ötödik könyve",
		"Józsué - Joshua",
		"A bírák - Judges",
		"Ruth",
		"Sámuel első - 1 Samuel",
		"Sámuel második - 2 Samuel",
		"A királyok első - 1 Kings",
		"A királyok második - 2 Kings",
		"A krónikák első - 1 Chronicles",
		"A krónikák második - 2 Chronicles",
		"Ezsdrás - Ezra",
		"Nehémiás - Nehemiah",
		"Eszter - Esther",
		"Jób - Job",
		"A zsoltárok - Psalms",
		"A példabeszédek - Proverbs",
		"A prédikátor - Ecclesiastes",
		"Énekek - Songs of Solomon",
		"Ézsaiás - Isaiah",
		"Jeremiás - Jeremiah",
		"Jeremiás siralmai - Lamentaions",
		"Ezékiel - Ezekiel",
		"Dániel - Daniel",
		"Hóseás - Hosea",
		"Jóel - Joel",
		"Ámósz - Amos",
		"Abdiás - Obadiah",
		"Jónás - Jonah",
		"Mikeás - Micah",
		"Náhum - Nahum",
		"Habakuk - Habakkuk",
		"Zofóniás - Zephaniah",
		"Haggeus - Haggai",
		"Zakariás - Zechariah",
		"Malakiás - Malachi",
		"Máté - Matthew",
		"Márk - Mark",
		"Lukács - Luke",
		"János - John",
		"Az apostolok cselekedetei - Acts",
		"Rómaiakhoz - Romans",
		"1 korinthusiakhoz - 1 Corinthians",
		"2 korinthusiakhoz - 2 Corinthians",
		"Galatákhoz - Galatians",
		"Efezusiakhoz - Ephesians",
		"Filippiekhez - Philippians",
		"Kolosséiakhoz - Colossians",
		"1 Thesszalonikaiakhoz - 1 Thessalonians",
		"2 Thesszalonikaiakhoz - 2 Thessalonians",
		"1 Timóteushoz - 1 Timothy",
		"2 Timóteushoz - 2 Timothy",
		"Tituszhoz",
		"Filemonhoz - Philemon",
		"Zsidókhoz - Hebrews",
		"Jakab - James",
		"Péter első - 1 Peter",
		"Péter második - 2 Peter",
		"János első - 1 John",
		"János második - 2 John",
		"János harmadik - 3 John",
		"Júdás - Jude",
		"Jelenések könyve - Revelation"
		};

	
	public static String vinames[] = {
		"Kinh Thánh",
		"ra",
		"chương",
		"cuốn sách",
		"di chúc",
		"văn bản",
		"chọn",
		"Cựu Ước",
		"Tân Ước",
		"thánh thi",
		"Tin Mừng",
		//4 добавленных значения ниже ///////////////////////
		"Kết quả T́m kiếm",				//<string name="findresults">
		"diêm",							//<string name="matches">
		"Bài thơ",						//<string name="poem">
		"Tìm"							//<string name="searchbutton">
		};

		public static String vibible[] = {

		"Sáng-thế Ký",
		"Xuất Ê-díp-tô Ký",
		"Lê-vi Ký",
		"Dân-số Ký",
		"Phục-truyền Luật-lệ Ký",
		"Giô-suê",
		"Các Quan Xét",
		"Ru-tơ",
		"1 Sa-mu-ên",
		"2 Sa-mu-ên",
		"1 Các Vua",
		"2 Các Vua",
		"1 Sử-ký",
		"2 Sử-ký",
		"Ê-xơ-ra",
		"Nê-hê-mi",
		"Ê-xơ-tê",
		"Gióp",
		"Thi-thiên",
		"Châm-ngôn",
		"Truyền-đạo",
		"Nhã-ca",
		"Ê-sai",
		"Giê-rê-mi",
		"Ca-thương",
		"Ê-xê-chi-ên",
		"Đa-ni-ên",
		"Ô-sê",
		"Giô-ên",
		"A-mốt",
		"Áp-đia",
		"Giô-na",
		"Mi-chê",
		"Na-hum",
		"Ha-ba-cúc",
		"Sô-phô-ni",
		"A-ghê",
		"Xa-cha-ri",
		"Ma-la-chi",
		"Ma-thi-ơ",
		"Mác",
		"Lu-ca",
		"Giăng",
		"Công-vụ các Sứ-đồ",
		"Rô-ma",
		"1 Cô-rinh-tô",
		"2 Cô-rinh-tô",
		"Ga-la-ti",
		"Ê-phê-sô",
		"Phi-líp",
		"Cô-lô-se",
		"1 Tê-sa-lô-ni-ca",
		"2 Tê-sa-lô-ni-ca",
		"1 Ti-mô-thê",
		"2 Ti-mô-thê",
		"Tít",
		"Phi-lê-môn",
		"Hê-bơ-rơ",
		"Gia-cơ",
		"1 Phi-e-rơ",
		"2 Phi-e-rơ",
		"1 Giăng",
		"2 Giăng",
		"3 Giăng",
		"Giu-đe",
		"Khải-huyền"

		};
	

	public static String dunames[] = {
		"Bijbel",
		"uitgang",
		"hoofdstuk",
		"boek",
		"testament",
		"tekst",
		"kiezen",
		"Oude Testament",
		"Nieuwe Testament",
		"PSALM",
		"Evangelie",
		//4 добавленных значения ниже ///////////////////////
		"Zoekresultaten",				//<string name="findresults">
		"Wedstrijden",					//<string name="matches">
		"Gedicht",						//<string name="poem">
		"Vind"							//<string name="searchbutton">
		};

		public static String dubible[] = {

		"Genesis",
		"Exodus",
		"Leviticus",
		"Numberi",
		"Deuteronomium",
		"Jozua",
		"Richtere",
		"Ruth",
		"1 Samuël",
		"2 Samuël",
		"1 Koningen",
		"2 Koningen",
		"1 Kronieken",
		"2 Kronieken",
		"Ezra",
		"Nehemia",
		"Esther",
		"Job",
		"Psalmen",
		"Spreuken",
		"Prediker",
		"Hooglied",
		"Jesaja",
		"Jeremia",
		"Klaagliederen",
		"Ezechiël",
		"Daniël",
		"Hosea",
		"Joël",
		"Amos",
		"Obadja",
		"Jona",
		"Micha",
		"Nahum",
		"Habakuk",
		"Zefanja",
		"Haggaï",
		"Zacharia",
		"Maleachi",
		"Mattheüs",
		"Markus",
		"Lukas",
		"Johannes",
		"Handelingen",
		"Romeinen",
		"1 Corinthiërs",
		"2 Corinthiër",
		"Galaten",
		"Efeziërs",
		"Filippenzen",
		"Colossenzen",
		"1 Thessalonicenzen",
		"2 Thessalonicenzen",
		"1 Timotheüs",
		"2 Timotheüs",
		"Titus",
		"Filémon",
		"Hebreeën",
		"Jakobus",
		"1 Petrus",
		"2 Petrus",
		"1 Johannes",
		"2 Johannes",
		"3 Johannes",
		"Judas",
		"Openbaring"
		};	
	
	public static String tamnames[] = {
		"பரிசுத்த வேதாகமம்",
		"வெளியேறும்",
		"அத்தியாயம்",
		"புத்தகம்",
		"உயில்",
		"உரை",
		"தேர்வு",
		"பழைய ஏற்பாடு",
		"புதிய ஏற்பாடு",
		"சங்கீதம்",
		"நற்செய்தி",
		//4 добавленных значения ниже ///////////////////////
		"தேடல் முடிவுகள்",				//<string name="findresults">
		"ஆட்டங்கள்",					//<string name="matches">
		"கவிதை",					//<string name="poem">
		"தேடு"						//<string name="searchbutton">
		};

		public static String tambible[] = {
		"ஆதியாகமம்",
		"யாத்திராகமம்",
		"லேவியராகமம்",
		"எண்ணாகமம்",
		"உபாகமம்",
		"யோசுவா",
		"நியாயாதிபதிகள்",
		"ரூத்",
		"1 சாமுவேல்",
		"2 சாமுவேல்",
		"1 இராஜாக்கள்",
		"2 இராஜாக்கள்",
		"1 நாளாகமம்",
		"2 நாளாகமம்",
		"எஸ்றா",
		"நெகேமியா",
		"எஸ்தர்",
		"யோபு",
		"சங்கீதம்",
		"நீதிமொழிகள்",
		"பிரசங்கி",
		"உன்னதப்பாட்டு",
		"ஏசாயா",
		"எரேமியா",
		"புலம்பல்",
		"எசேக்கியேல்",
		"தானியேல்",
		"ஓசியா",
		"யோவேல்",
		"ஆமோஸ்",
		"ஒபதியா",
		"யோனா",
		"மீகா",
		"நாகூம்",
		"ஆபகூக்",
		"செப்பனியா",
		"ஆகாய்",
		"சகரியா",
		"மல்கியா",
		"மத்தேயு",
		"மாற்கு",
		"லுூக்கா",
		"யோவான்",
		"அப்போஸ்தலருடைய நடபடிகள்",
		"ரோமர்",
		"1 கொரிந்தியர்",
		"2 கொரிந்தியர்",
		"கலாத்தியர்",
		"எபேசியர்",
		"பிலிப்பியர்",
		"கொலோசெயர்",
		"1 தெசலோனிக்கேயர்",
		"2 தெசலோனிக்கேயர்",
		"1 தீமோத்தேயு",
		"2 தீமோத்தேயு",
		"தீத்து",
		"பிலேமோன்",
		"எபிரெயர்",
		"யாக்கோபு",
		"1 பேதுரு",
		"2 பேதுரு",
		"1 யோவான்",
		"2 யோவான்",
		"3 யோவான்",
		"யூதா",
		"வெளிப்படுத்தின விசேஷம்"
		};
	
public static String konames[] = {
"성경",
"아웃",
"머리",
"도서",
"규약",
"텍스트",
"선택",
"구약 성서",
"신약 성경",
"시",
"복음",
//4 добавленных значения ниже ///////////////////////
"검색 결과",				//<string name="findresults">
"성냥",					//<string name="matches">
"시",					//<string name="poem">
"발견"						//<string name="searchbutton">
};

public static String kobible[] = {
"창세기",
"출애굽기",
"레위기",
"민수기",
"신명기",
"여호수아",
"사사기",
"룻기",
"사무엘상",
"사무엘하",
"열왕기상",
"열왕기하",
"역대상",
"역대하",
"에스라",
"느헤미야",
"에스더",
"욥기",
"시편",
"잠언",
"전도서",
"아가",
"이사야",
"예레미야",
"예레미야 애가",
"에스겔",
"다니엘",
"호세아",
"요엘",
"아모스",
"오바댜",
"요나",
"미가",
"나훔",
"하박국",
"스바냐",
"학개",
"스가랴",
"말라기",
"마태복음",
"마가복음",
"누가복음",
"요한복음",
"사도행전",
"로마서",
"고린도전서",
"고린도후서",
"갈라디아서",
"에베소서",
"빌립보서",
"골로새서",
"데살로니가전서",
"데살로니가후서",
"디모데전서",
"디모데후서",
"디도서",
"빌레몬서",
"히브리서",
"야고보서",
"베드로전서",
"베드로후서",
"요한1서",
"요한2서",
"요한3서",
"유다서",
"요한계시록"
};

	
	public static String japnames[] = {
		"日本聖書",
		"終了する",
		"章",
		"本",
		"聖書",
		"テキスト",
		"選択する",
		"旧約聖書",
		"新約聖書",
		"賛美歌",
		"共観福音書",
		//4 добавленных значения ниже ///////////////////////
		"検索結果",				//<string name="findresults">
		"マッチ",					//<string name="matches">
		"詩",					//<string name="poem">
		"検索"					//<string name="searchbutton">
};
	
public static String japbible[] = {
	"創世記",
	"出エジプト記",
	"レビ記",
	"民数記",
	"申命記",
	"ヨシュア記",
	"士師記",
	"ルツ記",
	"サムエル記上",
	"サムエル記下",
	"列王記上",
	"列王記下",
	"代誌上",
	"歴代誌下",
	"エズラ記",
	"ネヘミヤ記",
	"エステル記",
	"ヨブ記",
	"詩編",
	"箴言",
	"コヘレトの言葉",
	"雅歌",
	"イザヤ記",
	"エレミヤ記",
	"哀歌",
	"エゼキエル記",
	"ダニエル記",
	"ホセア記",
	"ヨエル記",
	"アモス記",
	"オバデア記",
	"ヨナ記",
	"ミカ記",
	"ナホム記",
	"ハバクク記",
	"ゼファニヤ記",
	"ハガイ記",
	"ゼカリヤ記",
	"マラキ記",
	"マタイによる福音書",
	"マルコによる福音書",
	"ルカによる福音書",
	"ヨハネによる福音書",
	"使徒言行録",
	"ローマの信徒への手紙",
	"コリントの信徒への手紙一",
	"コリントの信徒への手紙二",
	"ガラテヤの信徒への手紙",
	"エフェソの信徒への手紙",
	"フィリピの信徒への手紙",
	"コロサイの信徒への手紙",
	"テサロニケの信徒への手紙一",
	"テサロニケの信徒への手紙二",
	"テモテへの手紙一",
	"テモテへの手紙二",
	"テトスへの手紙",
	"フィレモンへの手紙",
	"ヘブライ人への手紙",
	"ヤコブの手紙",
	"ペトロの手紙一",
	"ペトロの手紙二",
	"ヨハネの手紙一",
	"ヨハネの手紙二",
	"ヨハネの手紙三",
	"ユダの手紙",
	"ヨハネの黙示録"
};

	
	public static String hinnames[] = {
		"पवित्र बाइबिल",
		"बाहर",
		"अध्याय",
		"किताब",
		"टैस्टमैंट",
		"पाठ",
		"चुनें",
		"ओल्ड टैस्टमैंट",
		"नई टैस्टमैंट",
		"भजन",
		"इंजील",
		//4 добавленных значения ниже ///////////////////////
		"खोज परिणाम",				//<string name="findresults">
		"माचिस",					//<string name="matches">
		"कविता",					//<string name="poem">
		"खोज"					//<string name="searchbutton">
		};

	public static String aranames[] = {
		"الكتاب المقدس",
		"نفاد",
		"رئيس",
		"كتاب",
		"العهد",
		"نص",
		"اختر",
		"العهد القديم",
		"العهد الجديد",
		"مزمور",
		"إنجيل",
		//4 добавленных значения ниже ///////////////////////
		"نتائج البحث",				//<string name="findresults">
		"مباريات",				//<string name="matches">
		"آية",				//<string name="poem">
		"اكتشاف"				//<string name="searchbutton">
		};
	
	public static String hebnames[] = {
		"הקודש במקרא",
		"יציאה",
		"פרק",
		"ספר",
		"צוואה",
		"טקסט",
		"יבחר",
		"תנ'ך",
		"ברית חדשה",
		"תהילים",
		"הבשורות ",
		//4 добавленных значения ниже ///////////////////////
		"תוצאות חיפוש",				//<string name="findresults">
		"גפרורים",				//<string name="matches">
		"פסוק",				//<string name="poem">
		"למצוא"				//<string name="searchbutton">
		};
	
public static String runames[] = {
"Библия",
"выход",
"глава",
"книга",
"завет",
"текст",
"выбрать",
"Ветхий Завет",
"Новый Завет",
"псалом",
"Евангелие",
//4 добавленных значения ниже ///////////////////////
"Результаты поиска",	//<string name="findresults">
"совпадений",			//<string name="matches">
"стих",					//<string name="poem">
"Найти"					//<string name="searchbutton">
};

public static String ennames[] = {
"The Bible",
"exit",
"chapter",
"book",
"testament",
"text",
"choose",
"Old Testament",
"New Testament",
"PSALM",
"Gospel",
//4 добавленных значения ниже ///////////////////////
"Search Results",	//<string name="findresults">
"matches",			//<string name="matches">
"poem",					//<string name="poem">
"Find"					//<string name="searchbutton">
};

public static String denames[] = {
"Bibel",
"ausgang",
"kapitel",
"buchen",
"testament",
"text",
"wählen",
"Altes Testament",
"Neues Testament",
"Psalmen",
"Evangelium",
//4 добавленных значения ниже ///////////////////////
"Suchergebnis",				//<string name="findresults">
"Streichhölzer",			//<string name="matches">
"Vers",						//<string name="poem">
"Finden"					//<string name="searchbutton">
};

public static String esnames[] = {
"Biblia",
"de salida",
"capítulo",
"libro",
"testamento",
"texto",
"seleccione",
"Antiguo Testamento",
"Nuevo Testamento",
"SALMO",
"Evangelio",
//4 добавленных значения ниже ///////////////////////
"Resultados de la búsqueda",		//<string name="findresults">
"cerillas",							//<string name="matches">
"verso",							//<string name="poem">
"Buscar"							//<string name="searchbutton">
};

public static String frnames[] = {
"La Bible",
"de sortie",
"chapitre",
"livre",
"testament",
"texte",
"sélectionnez",
"L'Ancien Testament",
"Le Nouveau Testament",
"PSAUME",
"Évangile",
//4 добавленных значения ниже ///////////////////////
"Résultats de la recherche",		//<string name="findresults">
"allumettes",						//<string name="matches">
"verset",							//<string name="poem">
"Trouver"							//<string name="searchbutton">
};

public static String itnames[] = {
"Bibbia",
"di uscita",
"capitolo",
"libro",
"testamento",
"testo",
"selezionare",
"Antico Testamento",
"Nuovo Testamento",
"SALMO",
"Vangelo",
//4 добавленных значения ниже ///////////////////////
"Risultati della ricerca",			//<string name="findresults">
"fiammiferi",						//<string name="matches">
"versetto",							//<string name="poem">
"Trovare"							//<string name="searchbutton">
};

public static String trnames[] = {
"Kutsal Kitap",
"çıktı",
"bölüm",
"kitap",
"antlaşma",
"metin",
"seçin",
"Eski Antlaşma",
"Yeni Antlaşma",
"MEZMUR",
"İncil",
//4 добавленных значения ниже ///////////////////////
"Arama Sonuçları",				//<string name="findresults">
"maçlar",						//<string name="matches">
"ayet",							//<string name="poem">
"Ara"							//<string name="searchbutton">
};

public static String ptnames[] = {
"Bíblia",
"saída",
"capítulo",
"livro",
"testamento",
"texto",
"selecione",
"Velho Testamento",
"Novo Testamento",
"SALMO",
"Evangelho",
//4 добавленных значения ниже ///////////////////////
"Resultados da Pesquisa",			//<string name="findresults">
"fósforos",							//<string name="matches">
"verso",							//<string name="poem">
"Encontrar"							//<string name="searchbutton">
};

public static String grnames[] = {
"Αγία Γραφή",
"εξόδου",
"kεφάλαιο",
"bιβλίο",
"Διαθήκη",
"κείμενο",
"επιλέξτε",
"Παλαιά Διαθήκη",
"Καινή Διαθήκη",
"ΨAΛMOΣ",
"Ευαγγέλιο",
//4 добавленных значения ниже ///////////////////////
"Αποτελέσματα αναζήτησης",			//<string name="findresults">
"σπίρτα",							//<string name="matches">
"στίχος",							//<string name="poem">
"Βρίσκω"							//<string name="searchbutton">
};


public static String zhnames[] = {
"简体中文和合本",
"输出",
"章",
"图书",
"约全书",
"文本",
"选择",
"旧约全书",
"新约全书",
"章",
"福音书",
//4 добавленных значения ниже ///////////////////////
"搜索结果",			//<string name="findresults">
"火柴",							//<string name="matches">
"诗",							//<string name="poem">
"发现"							//<string name="searchbutton">
};

String names() {
return "test";
}

}

